language: node_js
node_js:
  - "14"
dist: trusty

addons:
  chrome: stable

cache:
  directories:
      - ./node_modules

sudo: required
branches:
  only:
  - master

install:
  - npm install

before_script:
  - npm install -g @angular/cli

jobs:
  include:
    - stage: check
      name: Check Validity
      script: 
        - ng lint
        - ng build --prod --base-href https://see.pete.run/
        - npm run test-headless
    - stage: production
      name: Deploy To Production
      script:
        - ng build --prod --base-href https://see.pete.run/
      deploy:
        provider: firebase
        token:
          secure: "bHWgGxWwoXLf6aUwBnvBHzXxnyKnJcxuVgXcE8yb83U7Pps8YA8x+dHGPaTTUIeLexhtXxD/eP/Uwq0c1CfzgihAc4pdzeHe4R7pehK/8ufE5Oj7bvV6gz3toRx4zcpGqhvMiKBgk/NurM7gWetTVlQAAkMKANK6aXskynDpMjZM8+bLtddGKRdzZzPfV0EX/aBbzBLb87Q2A0d6IU2CQ6tB1PRLcYLY3USB9BT9gbux8O4ItjnoQeDYkUL6/HUzAP4INCwwV9xqiYNn+1IeevGHdTLlN9Uwru3jr8MEGfDWw4NJ5kh75XcZD2gSGHtTRu8b+jjAo6kZBq5gPch8eEgzc1LSIMBgnIe8OfrDLt8kCy3PchQ/uD0CqSpF/FoAr9sDzndCmLmllooOV9evIbrQvnD6apdE3+r1NzRcLj/DI2lQGvd2fH69GGi536eXKUCDwHjzSvx7dkZmvCN9DhKPGN6qtSHDQf2CMji/tqe8XjsAWh/gpmOSJbsCdD6O10NC/nBo1PAgk5hUcudWxZgTWQr4ugHcPZ6sXQqlRmYhg8KzHybCloy+TImNlkFEgqeIqNoYzVg35oksQsFQdA4XauTnIByGMZvdkqvXFuFVDVSONIn35qaaWt5TtXYuvtnFot1uKrJIvmMGjiILJkPolZeGxCLIGBOVDp8ju3A="
        project: see-pete-run