language: node_js
node_js:
  - "10"
dist: trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
      - ./node_modules

sudo: required
branches:
  only:
  - master

install:
  - npm install

before_script:
  - npm install -g @angular/cli

script:
- ng lint
- ng build --prod --base-href https://see.pete.run/
- npm run test-headless