language: node_js
node_js:
  - "14"
dist: trusty

addons:
  chrome: stable

cache:
  directories:
      - ./node_modules

sudo: required
branches:
  only:
  - master

install:
  - npm install

before_script:
  - npm install -g @angular/cli

jobs:
  include:
    - stage: check
      name: Check Validity
      script: 
        - ng lint
        - ng build --prod --base-href https://see.pete.run/
        - npm run test-headless
    - stage: production
      name: Deploy To Production
      script:
        - ng build --prod --base-href https://see.pete.run/
      deploy:
        provider: firebase
        skip_cleanup: true
        token:
          secure: "ggkpPRWaMV2CJx2KyOCCCXyFKV3tOCfxWibG8jM7PQ7+CbPemFsuJbmRuW5hHvZysfEbEr5pxxTLPPsEDdAyhBKtg+I3/ki1Y+P+IQhOTFMgRugQmW23h2pIBwsBRsOaQ8w/fzM/ve0UgJxzzLYxbOjr/VB5yQlWlQ8cdSqAeqSLO/GqYW6WrCZuMqvIVsgs68swgKF9K3o/ixvtDp5sM2Dmor9ETI5FoCdD/2LtBIN1hwrGHJ5nO/Z3fN+KITJFLyIdRLeIdydmWbVjlQCQQIPnl4qJJCkEUDKkWqcr9c5AF1i44zEOhGyH6lrSU5z/RZKy6kLUZxJLUhBwFXSjQYzYNwdIPUOsY93TDgQPIfQCtZlTDztdx6Igyj2GF/OGWo5po/9t5x+cephxFzN366B6iwue8I0ZMInYpgnqtA2rJqWumIivkU832ppxZ6XORNaSM+0SKKLDOLFTC6L00mE6i/APORpjgoU94cUFMVXbI6PPfmtoBSV+Lce3ma6cLqwr9RS24uisp+pLe4ToxW78Fcu7B5HFq16w40UfkdCWlJiRGBCbTfqsj6ilM4Eeq1fSL/CMIUj8qPLB5K/FNDkoT2MkVmNhWCvOEv1BAQuk/H2RgCkg0nJB49F/8PsLsfDS77XZSlMjusUfLguLCr26zDOQ0hRBSuzEUxKCnA4="
        project: see-pete-run