language: node_js
node_js:
  - "10"
dist: trusty

addons:
  chrome: stable

cache:
  directories:
      - ./node_modules

sudo: required
branches:
  only:
  - master

install:
  - npm install

before_script:
  - npm install -g @angular/cli

jobs:
  include:
    - stage: analysis
      name: Linting
      script: ng lint
    - stage: build
      name: Angular Build
      script: ng build --prod --base-href https://see.pete.run/
    - stage: test
      name: Unit Tests
      script: npm run test-headless